### ISSUE TITLE
Great Widget

### ISSUE THREAD

**Issue by moosemedia** [craigcoles/lastfm-widget#1]
I love this widget, I would really like to tweak this or create another one to display the last 5-10 played tracks from Last FM. Are you able to help with this?

**Comment by craigcoles** [comment]
@moosemedia I will look into this for you, should be easy enough to add some config options for this.

**Comment by craigcoles** [comment]
@moosemedia There is a new [branch](https://github.com/craigcoles/lastfm-widget/tree/feature/show_more_songs) which I'll be making the changes on, I'll keep you updated with progress :+1:

**Comment by moosemedia** [comment]
@craigcoles Thanks alot. I am hoping to have this running side by side with your other widget!

**Comment by moosemedia** [comment]
@craigcoles any progress on this I downloaded the zip, I had to change some file and data names because I want to have the two widgets running side by side. When I run dashing it outputs the results of the URL into the terminal.

**Comment by craigcoles** [comment]
@moosemedia I have not made any progress since, due to busy with work etc! I'll hopefully have a look at this over the weekend and get back to you!

**Comment by moosemedia** [comment]
Hey @craigcoles have you made any progress on this? I know its been a while.
